# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 7.1"
gem "sqlite3"

# Reference the parent gem
gem "activestorage-ocr", path: "../.."

group :test do
  gem "minitest"
end
